package com.Argano.enums;

public enum ConfigProperties {

	URL, OVERRIDEREPORTS, BROWSER, PASSEDSTEPSSCREENSHOTS, FAILEDSTEPSSCREENSHOTS, SKIPPEDSTEPSSCREENSHOTS,
	RETRYFAILEDTESTS, SENDRESULTINMAIL, TOEMAILRECIPIENT, CCEMAILRECIPIENT, BCCEMAILRECIPIENT;

}
